language: php
php: 
  - 5.4
  - 5.5
  - 5.6

before_script: composer install
after_script:
  - CODECLIMATE_REPO_TOKEN=ae6ddb5fa1b6ecb3a27e0e0d1d746ccc0cc6912a200bc7905029d61de56c7aba ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code C"